import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const scssDir = path.join(projectRoot, "scss");
const srcImagesDir = path.join(projectRoot, "src", "images");
const releaseDir = path.join(projectRoot, "release");
const releaseImagesDir = path.join(releaseDir, "images");
const indexFile = path.join(scssDir, "index.scss");
const baseFile = path.join(scssDir, "base.scss");
const sassCli = path.join(projectRoot, "node_modules", "sass", "sass.js");
const jsdelivrBase = "https://cdn.jsdelivr.net/gh/sansui233/ao3-flat-skin";

function listScssPrefix(prefix) {
  return fs
    .readdirSync(scssDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.startsWith(prefix) && entry.name.endsWith(".scss"))
    .map((entry) => entry.name.slice(prefix.length, -".scss".length))
    .sort((a, b) => a.localeCompare(b, "en"));
}

function writeIndex(theme, language = null) {
  const themes = listScssPrefix("theme-");
  const languages = listScssPrefix("lang-");
  const lines = [
    "// AO3 skin release build entry. Generated by scripts/build.mjs.",
    "// Theme switch:",
    ...themes.map((name) => `${name === theme ? "" : "// "}@use "theme-${name}";`),
    "",
    "// lang(optional)",
    ...languages.map((name) => `${name === language ? "" : "// "}@use "lang-${name}";`),
    "",
    '@use "base";',
    "",
  ];

  fs.writeFileSync(indexFile, lines.join("\n"), "utf8");
}

function buildOutputName(theme, language = null) {
  return `flat-${theme}${language ? `-${language}` : ""}.css`;
}

function runSass(outputFile) {
  const result = spawnSync(
    process.execPath,
    [sassCli, "--no-source-map", indexFile, outputFile],
    {
      cwd: projectRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      windowsHide: true,
    },
  );

  if (result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);

  if (result.status !== 0) {
    throw new Error(`sass failed with exit code ${result.status}`);
  }
}

function rewriteImagesetUrl(outputFile, theme, baseHasImageset) {
  if (!baseHasImageset) {
    console.warn("[build] warning: scss/base.scss does not contain /images/imageset.png");
    return;
  }

  const themedImageName = `imageset-${theme}.png`;
  const themedImageFile = path.join(srcImagesDir, themedImageName);

  if (!fs.existsSync(themedImageFile)) {
    console.warn(
      `[build] warning: ${path.relative(projectRoot, themedImageFile)} not found; leaving /images/imageset.png unchanged in ${path.basename(outputFile)}`,
    );
    return;
  }

  const css = fs.readFileSync(outputFile, "utf8");
  const cdnUrl = `${jsdelivrBase}/images/${themedImageName}`;
  fs.writeFileSync(outputFile, css.replaceAll("/images/imageset.png", cdnUrl), "utf8");
}

function copyImages() {
  if (!fs.existsSync(srcImagesDir)) {
    console.warn("[build] warning: src/images not found; release/images was not created");
    return;
  }

  fs.cpSync(srcImagesDir, releaseImagesDir, { recursive: true });
}

function prepareReleaseDir() {
  fs.rmSync(releaseDir, { recursive: true, force: true });
  fs.mkdirSync(releaseDir, { recursive: true });
}

const themes = listScssPrefix("theme-");
const languages = listScssPrefix("lang-");

if (themes.length === 0) {
  throw new Error("No theme-*.scss files found in scss/");
}

if (!fs.existsSync(sassCli)) {
  throw new Error("Sass CLI not found. Run pnpm install first.");
}

const originalIndex = fs.readFileSync(indexFile, "utf8");
const baseHasImageset = fs.readFileSync(baseFile, "utf8").includes("/images/imageset.png");

prepareReleaseDir();

try {
  for (const theme of themes) {
    const combinations = [null, ...languages];

    for (const language of combinations) {
      const outputName = buildOutputName(theme, language);
      const outputFile = path.join(releaseDir, outputName);

      writeIndex(theme, language);
      runSass(outputFile);
      rewriteImagesetUrl(outputFile, theme, baseHasImageset);
      console.log(`[build] wrote release/${outputName}`);
    }
  }
} finally {
  fs.writeFileSync(indexFile, originalIndex, "utf8");
}

copyImages();
console.log("[build] copied release/images");
